version: '3.5'

services:
  node:
    build: .
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db_postgres
  db_postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "mysales"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"