version: '3.5'

services:
  node:
    build: .
    command: npm start
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
  db_postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "mysales"
    volumes:
      - ./db_data:/data/postgres
    ports:
      - "5432:5432"